### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by Mrkkew** [bitreidgroup/Modality-Confusion-Learning#2]
When I used the given code for training, I got the following error: 
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
What is the possible reason for that?

**Comment by bitreidgroup** [comment]
We have not met this before. Maybe you can strictly check the version of Pytorch Library and NVIDIA CuDNN.

**Comment by vk-rrr** [comment]
> When I used the given code for training, I got the following error: RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True). What is the possible reason for that?

请问怎么解决这个问题？
